### ISSUE TITLE
Feature Request: Add message_subject parameter to MaintenanceSchedule method

### ISSUE THREAD

**Issue by floudet** [statusio/statusio-python#1]
According to the official Status.io API v2 documentation, `maintenance/schedule` accepts an optional `message_subject` parameter which is the message subject for email notifications. This parameter is however absent from this library. Would be nice to have it added.

http://docs.statusio.apiary.io/#reference/maintenance/create-maintenance/maintenance/schedule

**Comment by joet3ch** [comment]
The message_subject parameter will be added in the future. Thanks for your feedback.
