### ISSUE TITLE
NameError: global name 'Error' is not defined

### ISSUE THREAD

**Issue by kalkehcoisa** [statusio/statusio-python#2]
We're starting to use statusio at work and we're getting the following error:
> "NameError: global name 'Error' is not defined"
in statusio/api.py

I checked the file and "Error" is defined nowhere.
Could someone make a fix for this? Because I don't know the intended error message format.
Well, or explain what's the planed behaviour to it, so I send a pull request fixing.

**Comment by joet3ch** [comment]
Thanks for reporting this issue. A fix has been applied in the latest commit.

**Comment by kalkehcoisa** [comment]
Thank you very much! ;)
