### ISSUE TITLE
Incorrect type of parameters for CreateIncident function

### ISSUE THREAD

**Issue by dancvrcek** [statusio/statusio-python#3]
You seem to have incorrect type of variables for the CreateIncident function, which results in HTTP responses 400 - "Bad Request".

It is all these parameters, which have to be strings, rather than integers (I left values in as just copy&pasting here):
notify_email="0", notify_sms="0",
                                notify_webhook="0", social="0", irc="0", hipchat="0", slack="0",
                                all_infrastructure_affected="0"

**Comment by joet3ch** [comment]
Thanks for reporting.

This issue has been fixed.
