### ISSUE TITLE
api_id not found

### ISSUE THREAD

**Issue by tyagian** [statusio/statusio-python#8]
I don't see what should be api_id from the documentation. 
It seems, it should be integer only. 

The sample example: 

import statusio
api = statusio.Api(api_id='api_id', api_key='api_key')
summary = api.StatusSummary('status_page_id')    
print(summary)

I get error here: 
    summary = api.StatusSummary(api_id)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/statusio/api.py", line 890, in StatusSummary
    data = json.loads(resp.content.decode('utf-8'))
AttributeError: 'int' object has no attribute 'content'

 I am not sure exactly where to find api_id? I don't see any other examples using it.

**Comment by joet3ch** [comment]
StatusSummary accepts STATUSPAGE_ID

**Comment by tyagian** [comment]
Do you mean STATUSPAGE_ID can be mentioned in api_id as well?
I was asking about API_ID.

**Comment by joet3ch** [comment]
Please contact Status.io Support. They will be able to help further.
